name: Metrics
on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: mobinrezaeifar
          filename: metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Berlin
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 12
          plugin_languages_sections: most-used
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_lines: yes
          plugin_topics: yes
          plugin_topics_limit: 12
